### ISSUE TITLE
[python] -o - should output to stdout

### ISSUE THREAD

**Issue by mkevenaar** [PeterMosmans/security-scripts#19]
root@$host:~# analyze_hosts --ssl -o - $server
analyze_hosts.py version 0.4
[+] 09:53:16 21-01-2016 Working on $server (1 of 1)
[+] Starting nmap scan
    Found open ports [80, 443]
09:54:06 21-01-2016 Output saved to -

**Comment by PeterMosmans** [comment]
Thanks for the suggestion, the stdout option will be added in a future version

**Comment by PeterMosmans** [comment]
It took a while, but it's finally implemented in version 0.18. The output will be shown by default (there will be an option to (`--quiet') the console output
