### ISSUE TITLE
Few enhancements for easier installation.

### ISSUE THREAD

**Issue by StefanVink** [PeterMosmans/security-scripts#20]
Hi Peter,
Thanks for the great tool. I am using Kali 2.0 x64 and had a few issues to get it working. It could be helpful if there were a few prerequisites checks when running the script for the first time:
- whois is not installed by default in Kali
- virtualenv is not installed by default in Kali

After this the script worked. Thanks again.

**Comment by PeterMosmans** [comment]
Hi @StefanVink , thanks for your feedback. I updated the documentation.

Cheers,

Peter
