### ISSUE TITLE
Output breaks terminal

### ISSUE THREAD

**Issue by maq123** [PeterMosmans/security-scripts#38]
Running scan with the following command:
```
./analyze_hosts.py 10.0.0.0/24 --compact --threads 2 -o scan
```

Leaves the terminal no echoing typed characters after all, bash's ```reset``` is necessary to get it back to previous state.

**Comment by PeterMosmans** [comment]
Hi @maq123 , thanks for the report. Could you please add the output of the verbose/debug command, to see which tools are being used ? I suspect that it has something to do with those.

Thanks!

**Comment by maq123** [comment]
Here it is!

[logfile.txt](https://github.com/PeterMosmans/security-scripts/files/1170362/logfile.txt)

**Comment by PeterMosmans** [comment]
Closing, as Python3 is now the default compiler
