### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by AndrewBuiltThis** [PeterMosmans/security-scripts#40]
Howdy Peter!

First off, thanks for this library -- it's awesome. 

I saw in the documentation you said that this should work in both Python 2 and Python 3. Unfortunately I'm having an issue getting this operational in that capacity as the python-wappalyzer library appears to only be supported in Python 2. I tried using some of the Python 3 'variants' of the library, but those don't satisfy your module's requirement check.

Am I missing something or is this an actual issue / a mistake in the documentation?

Thanks!
A

**Comment by PeterMosmans** [comment]
Hi @AndrewBuiltThis , Python3 is now used by default.
Note that ``--framework`` will still not work yet. I'll ping the maintainer, as the library has provisional Python3 support, but not the distributed version
