### ISSUE TITLE
Disabling --framework due to missing Python library

### ISSUE THREAD

**Issue by Damuammu** [PeterMosmans/security-scripts#41]
any idea for below issue

Disabling --framework due to missing Python library

thanks

**Comment by Damuammu** [comment]
here is installation log

pip3 install -r requirements.txt
Collecting droopescan>=1.41.2 (from -r requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/04/92/23dca4416ddc9246f7ebbdfe9fa00843ab71f15842beb037f84e2287f9d0/droopescan-1.41.3-py2.py3-none-any.whl (504kB)
    100% |████████████████████████████████| 512kB 229kB/s 
Requirement already satisfied: python-nmap>=0.5.0.post1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (0.6.1)
Collecting python-wappalyzer>=0.2.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/34/30/1d686c4de1f3b67286d187488c404afa77fdb14e26f60a9ca5c890c74f05/python-Wappalyzer-0.2.2.tar.gz
Requirement already satisfied: requests>=2.9.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.21.0)
Collecting cement<2.6.99,>=2.6 (from droopescan>=1.41.2->-r requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d9/a6/eb2ea42c960400f3eb71d2e3e2f0b478d83ad8ad2218794e0037e098fedd/cement-2.6.2.tar.gz (140kB)
    100% |████████████████████████████████| 143kB 149kB/s 
Collecting pystache (from droopescan>=1.41.2->-r requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/pystache-0.5.4.tar.gz (75kB)
    100% |████████████████████████████████| 81kB 753kB/s 
Collecting futures (from droopescan>=1.41.2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz
Collecting BeautifulSoup==3.2.1 (from python-wappalyzer>=0.2.2->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-76saedjc/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-76saedjc/BeautifulSoup/

**Comment by PeterMosmans** [comment]
Hi @Damuammu thanks for the report. Unfortunately wappalyzer hasn't been properly updated for Python 3 yet. Please install it manually:

```
pip3 install https://github.com/KhasMek/python-Wappalyzer@python3
```

**Comment by Damuammu** [comment]
Hi Peter ,

I have tried ur suggestion . But still it's failing.
root@kali:~/Tools/workshop/seurity-analyzer/security-scripts# apt-get -y
install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (18.1-5).
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.


root@kali:~/Tools/workshop/seurity-analyzer/security-scripts# pip3 install
https://github.com/KhasMek/python-Wappalyzer@python3
bash: pip3: command not found

Please help.

Thanks
Damodar

**Comment by PeterMosmans** [comment]
Hi @Damuammu is this still an issue? It looks like the alias `pip3` doesn't exist. Try the above command, and replacing `pip3` with `pip`.

**Comment by tristanlatr** [comment]
Hello, Just to inform you that python-wappalyzer has been ported to python3 so I think this issue can be closed :)
The repo is https://github.com/chorsley/python-Wappalyzer

**Comment by PeterMosmans** [comment]
Thanks, will do
