### ISSUE TITLE
Error while executing ['nmap', '--version']: [Errno 2] No such file or directory: 'nmap'

### ISSUE THREAD

**Issue by techindustan** [PeterMosmans/security-scripts#44]
I'm getting `Error while executing ['nmap', '--version']: [Errno 2] No such file or directory: 'nmap'` when I run `analyze_hosts.py` file with the host IP.

**Comment by PeterMosmans** [comment]
Hi @techindustan is `nmap` installed, and available in your search path? Which operating system ?
What does `which nmap` say ?

**Comment by PeterMosmans** [comment]
Closing this issue
