### ISSUE TITLE
nmap module attributes

### ISSUE THREAD

**Issue by zencharcoal** [PeterMosmans/security-scripts#46]
I received the error below in the analyze_hosts.py file on several occasions.

Perhaps it has to do with the version of the nmap module having different attribtutes, but I am strugging to get it to run properly. While the script doesn't error out, it will loop without finishing. 

This is a cool tool with a lot of possibilities. Thanks for releasing it. 

![image](https://user-images.githubusercontent.com/63509228/124269709-883a2f00-db3b-11eb-9c80-2e967626ccbb.png)

**Comment by zencharcoal** [comment]
Ahh, This is definitely a versioning issue. That's my bad.

**Comment by PeterMosmans** [comment]
Hi @zencharcoal - I'm glad to hear you solved the issue. Let me know if there are any other issues, happy to help...
